---
- name: install plugins
  command: {{elasticsearch_plugin_bin}} {{java_opts}} install {{item.plugin}}
  args:
    creates: {{elasticsearch_plugin_dir}}/{{item.creates}}
  with_items: {{elasticsearch_plugins}}
    
