---
- name: install plugins
  with_items: '{{elasticsearch_plugins | default([])}}'
  shell: >-
    {{elasticsearch_plugin_esdir}}/bin/elasticsearch-plugin $JAVA_OPTS install {{item.plugin}}
  args:
    creates: '{{elasticsearch_plugin_esdir}}/plugins/{{item.creates|default(item.plugin)}}'
    
